console.log("essa é uma tela do console");
var primeiro_nome="goiaba ";
var ultimo_nome="PONCÃ";
var nome_completo=primeiro_nome.concat(ultimo_nome);
console.log(nome_completo);
var substituto=nome_completo.replace("PONCÃ", "batata");
console.log(substituto);
var comprimento=ultimo_nome.length;
console.log("PONCÃ: "+comprimento);
var maiuscula=primeiro_nome.toUpperCase();
var minuscula=ultimo_nome.toLowerCase();
console.log(maiuscula+" "+minuscula);
var raiz=Math.sqrt(9);
console.log("raiz quadrada de 9 é "+raiz);
var max=Math.max(1, 9);
console.log("o numero maximo entre 1 e 56 é "+max);
var num1=3;
var num2=12;
var soma=num1+num2;
console.log("a soma é "+soma);
var sub=num2-num1;
console.log("a subtração é "+sub);
var mult=num1*num2;
console.log("a multiplicação é "+mult);
var div=num2/num1;
console.log("a divisão é "+div);